import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Footer } from "@/components/footer";
import { LandingPageHeader } from "@/components/landing-page-header";
import { ThemeProvider } from "@/components/theme-provider"
import { Analytics } from "@vercel/analytics/react"
import { SpeedInsights } from "@vercel/speed-insights/next"

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "A Global Warming App",
  description: "The climate is toast.",
};
// "Generated by create next app"

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.variable} antialiased`}>
        <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
          <div className="flex min-h-screen flex-col">
          <LandingPageHeader
            items={[
              { title: "Home", href: "/" },
              { title: "Local", href: "/local" },
              { title: "NDCs", href: "/ndc" },
              { title: "BTRs", href: "/btr" },
              { title: "WMO", href: "/wmo" },
              { title: "Take Action!", href: "https://www.mnd.gov.sg/docs/default-source/mnd-documents/publications-documents/climate-action-plan---take-action-today.pdf", external: true },
            ]}
          />
          <main className="flex-1">{children}</main>
          <Footer
            builtBy="Jovi"
            builtByLink="https://linktr.ee/sjove"
            githubLink="https://github.com/jovi-s"
            linkedinLink="https://www.linkedin.com/in/jovindersingh/"
          />
          </div>
        </ThemeProvider>
        <Analytics />
        <SpeedInsights />
      </body>
    </html>
  );
}